config/routes.rb
SqlLogging::Application.routes.draw do
  resources :book_details

  resources :books

end

app/models/book.rb
class Book < ActiveRecord::Base
  acts_as_paranoid
  attr_accessible :author, :price, :title
  has_many :book_details
end

app/models/book_detail.rb
class BookDetail < ActiveRecord::Base
  acts_as_paranoid
  attr_accessible :book, :detail

  default_scope{ where(paranoid_default_scope_sql).with_logging }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/book_details_controller.rb
class BookDetailsController < ApplicationController
  # GET /book_details
  # GET /book_details.json
  def index
    @book_details = BookDetail.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @book_details }
    end
  end

  # GET /book_details/1
  # GET /book_details/1.json
  def show
    @book_detail = BookDetail.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book_detail }
    end
  end

  # GET /book_details/new
  # GET /book_details/new.json
  def new
    @book_detail = BookDetail.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book_detail }
    end
  end

  # GET /book_details/1/edit
  def edit
    @book_detail = BookDetail.find(params[:id])
  end

  # POST /book_details
  # POST /book_details.json
  def create
    @book_detail = BookDetail.new(params[:book_detail])

    respond_to do |format|
      if @book_detail.save
        format.html { redirect_to @book_detail, notice: 'Book detail was successfully created.' }
        format.json { render json: @book_detail, status: :created, location: @book_detail }
      else
        format.html { render action: "new" }
        format.json { render json: @book_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /book_details/1
  # PUT /book_details/1.json
  def update
    @book_detail = BookDetail.find(params[:id])

    respond_to do |format|
      if @book_detail.update_attributes(params[:book_detail])
        format.html { redirect_to @book_detail, notice: 'Book detail was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_details/1
  # DELETE /book_details/1.json
  def destroy
    @book_detail = BookDetail.find(params[:id])
    @book_detail.destroy

    respond_to do |format|
      format.html { redirect_to book_details_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # GET /books
  # GET /books.json
  def index
    @books = Book.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_details_helper.rb
module BookDetailsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/book_details/_form.html.erb
<%= form_for(@book_detail) do |f| %>
  <% if @book_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book_detail.errors.count, "error") %> prohibited this book_detail from being saved:</h2>

      <ul>
      <% @book_detail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :detail %><br />
    <%= f.text_field :detail %>
  </div>
  <div class="field">
    <%= f.label :book %><br />
    <%= f.text_field :book %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/book_details/edit.html.erb
<h1>Editing book_detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @book_detail %> |
<%= link_to 'Back', book_details_path %>

app/views/book_details/index.html.erb
<h1>Listing book_details</h1>

<table>
  <tr>
    <th>Detail</th>
    <th>Book</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @book_details.each do |book_detail| %>
  <tr>
    <td><%= book_detail.detail %></td>
    <td><%= book_detail.book %></td>
    <td><%= link_to 'Show', book_detail %></td>
    <td><%= link_to 'Edit', edit_book_detail_path(book_detail) %></td>
    <td><%= link_to 'Destroy', book_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Book detail', new_book_detail_path %>

app/views/book_details/new.html.erb
<h1>New book_detail</h1>

<%= render 'form' %>

<%= link_to 'Back', book_details_path %>

app/views/book_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Detail:</b>
  <%= @book_detail.detail %>
</p>

<p>
  <b>Book:</b>
  <%= @book_detail.book %>
</p>


<%= link_to 'Edit', edit_book_detail_path(@book_detail) %> |
<%= link_to 'Back', book_details_path %>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Listing books</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Price</th>
    <th>Author</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @books.each do |book| %>
  <tr>
    <td><%= book.title %></td>
    <td><%= book.price %></td>
    <td><%= book.author %></td>
    <td><%= link_to 'Show', book %></td>
    <td><%= link_to 'Edit', edit_book_path(book) %></td>
    <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @book.title %>
</p>

<p>
  <b>Price:</b>
  <%= @book.price %>
</p>

<p>
  <b>Author:</b>
  <%= @book.author %>
</p>


<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SqlLogging</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>